sams/sams/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('samsApp.urls')),
    path('admin/', admin.site.urls),
    path('avatar/', include('avatar.urls')),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sams/samsApp/urls.py
from django.urls import path
from . import views
from .views import (
    CustomPasswordResetView,
    CustomPasswordResetDoneView,
    CustomPasswordResetConfirmView,
    CustomPasswordResetCompleteView
)



urlpatterns = [
    path('', views.home_view, name = "home_url"),
    path('accounts/login/', views.login_view, name='login_url'),
    path('logout/',views.logoutview, name='logout_url'),

    path('register/',views.register_view, name='register_url'), 

    path('student/<slug:stud_id>/attendance/', views.student_attendance, name='student_attendance_url'),
    path('student/<slug:stud_id>/<slug:course_id>/attendance/', views.student_attendance_detail, name='student_attendance_detail_url'),
    path('student/',views.student_view,name='student_home_url'),
    path('student/<slug:student_id>/notification', views.student_notification, name='student_notification_url'),

    path('teacher/',views.teacher_view,name='teacher_home_url'),
    path('teacher/<slug:teacher_id>/', views.t_clas, name='t_clas_url'),
    path('teacher/<int:assign_id>/Students/attendance/', views.t_student, name='t_student_url'),
    path('teacher/<int:assign_id>/ClassDates/', views.t_class_date, name='t_class_date_url'),
    
    path('teacher/<int:ass_c_id>/attendance/', views.t_attendance, name='t_attendance_url'),
    path('teacher/<int:ass_c_id>/Edit_att/', views.edit_att, name='edit_att_url'),
    path('teacher/<int:ass_c_id>/attendance/confirm/', views.confirm, name='confirm_url'),
  
    path('teacher/<slug:teacher_id>/notification', views.t_notification, name='t_notification_url'),
     
   
    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    
    path('teacher_change_password/', views.teacher_change_password, name='teacher_change_password'),
    path('student_change_password/', views.student_change_password, name='student_change_password'),
]

sams/samsApp/models.py
from django.db import models
import math
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.db.models.signals import post_save
from datetime import timedelta
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _
from django.utils import timezone


# Create your models here.
gender_choice = (
    ('Male', 'Male'),
    ('Female', 'Female')
)

time_slots = (
    ('9:00 - 11:00', '9:00 - 11:00'),
    ('9:00 - 1:00', '9:00 - 1:00'),
    ('9:00 - 12:00', '9:00 - 12:00'),

    ('2:00 - 4:00', '2:00 - 4:00'),
    ('2:00 - 5:00', '2:00 - 5:00'),
)


DAYS_OF_WEEK = (
    ('Monday', 'Monday'),
    ('Tuesday', 'Tuesday'),
    ('Wednesday', 'Wednesday'),
    ('Thursday', 'Thursday'),
    ('Friday', 'Friday'),
    ('Saturday', 'Saturday'),
)



class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_admin', True)
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    is_active = models.BooleanField(default=True)
    is_teacher = models.BooleanField(default=False)
    is_student = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    approved = models.BooleanField(_('Approved'), default = False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    def __str__(self):
        return self.email



class Dept(models.Model):
    id = models.CharField(primary_key=True, max_length=100)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Course(models.Model):
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE)
    id = models.CharField(primary_key=True, max_length=50)
    name = models.CharField(max_length=50)
    shortname = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Class(models.Model):
    id = models.CharField(primary_key=True, max_length=100)
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE)
    section = models.CharField(max_length=100)
    sem = models.IntegerField()

    class Meta:
        verbose_name_plural = 'classes'

    def __str__(self):
        d = Dept.objects.get(name=self.dept)
        return '%s : %d %s' % (d.name, self.sem, self.section)

class Admin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    gender = models.CharField(max_length=50, choices=gender_choice)
    date_of_birth = models.DateField(null=True)



class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    class_id = models.ForeignKey(Class, on_delete=models.CASCADE, null=True)
    USN = models.CharField(primary_key='True', max_length=100)
    gender = models.CharField(max_length=50, choices=gender_choice)
    date_of_birth = models.DateField(null=True)
    batch = models.CharField(max_length=50, default='B1')

    def __str__(self):
        return self.USN


class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE, null=True)
    gender = models.CharField(max_length=50, choices=gender_choice)
    date_of_birth = models.DateField(null=True)    

    def __str__(self):
        return self.user.first_name


class Assign(models.Model):
    class_id = models.ForeignKey(Class, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('course', 'class_id', 'teacher'),)

    def __str__(self):
        cl = Class.objects.get(id=self.class_id_id)
        cr = Course.objects.get(id=self.course_id)
        te = Teacher.objects.get(id=self.teacher_id)
        return '%s : %s : %s' % (te.user.first_name, cr.shortname, cl)


class AssignTime(models.Model):
    assign = models.ForeignKey(Assign, on_delete=models.CASCADE)
    period = models.CharField(max_length=50, choices=time_slots)
    day = models.CharField(max_length=15, choices=DAYS_OF_WEEK)


class AttendanceClass(models.Model):
    assign = models.ForeignKey(Assign, on_delete=models.CASCADE)
    date = models.DateField()
    status = models.IntegerField(default=0)

    class Meta:
        verbose_name = 'Attendance'
        verbose_name_plural = 'Attendance'


class Attendance(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    attendanceclass = models.ForeignKey(AttendanceClass, on_delete=models.CASCADE)
    date = models.DateField()
    status = models.BooleanField()

    def __str__(self):
        sname = Student.objects.get(name=self.student)
        cname = Course.objects.get(name=self.course)
        return '%s : %s' % (sname.user.first_name, cname.shortname)


class AttendanceTotal(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('student', 'course'),)

    @property
    def att_class(self):
        stud = Student.objects.get(USN=self.student)
        cr = Course.objects.get(name=self.course)
        att_class = Attendance.objects.filter(course=cr, student=stud, status='True').count()
        return att_class

    @property
    def total_class(self):
        stud = Student.objects.get(USN=self.student)
        cr = Course.objects.get(name=self.course)
        total_class = Attendance.objects.filter(course=cr, student=stud).count()
        return total_class

    @property
    def attendance(self):
        stud = Student.objects.get(USN=self.student)
        cr = Course.objects.get(name=self.course)
        total_class = Attendance.objects.filter(course=cr, student=stud).count()
        att_class = Attendance.objects.filter(course=cr, student=stud, status='True').count()
        if total_class == 0:
            attendance = 0
        else:
            attendance = round(att_class / total_class * 100, 2)
        return attendance

    @property
    def classes_to_attend(self):
        stud = Student.objects.get(USN=self.student)
        cr = Course.objects.get(name=self.course)
        total_class = Attendance.objects.filter(course=cr, student=stud).count()
        att_class = Attendance.objects.filter(course=cr, student=stud, status='True').count()
        cta = math.ceil((0.75 * total_class - att_class) / 0.25)
        if cta < 0:
            return 0
        return cta


class StudentCourse(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('student', 'course'),)
        verbose_name_plural = 'Marks'

    def __str__(self):
        sname = Student.objects.get(name=self.student)
        cname = Course.objects.get(name=self.course)
        return '%s : %s' % (sname.name, cname.shortname)

    def get_attendance(self):
        a = AttendanceTotal.objects.get(student=self.student, course=self.course)
        return a.attendance



class AttendanceRange(models.Model):
    start_date = models.DateField()
    end_date = models.DateField()

def daterange(start_date, end_date):
    for n in range(int((end_date - start_date).days)):
        yield start_date + timedelta(n)


days = {
    'Monday': 1,
    'Tuesday': 2,
    'Wednesday': 3,
    'Thursday': 4,
    'Friday': 5,
    'Saturday': 6,
}


@receiver(post_save, sender=AssignTime)
def create_attendance(sender, instance, created, **kwargs):
    if created:
        start_date = AttendanceRange.objects.all()[:1].get().start_date
        end_date = AttendanceRange.objects.all()[:1].get().end_date
        for single_date in daterange(start_date, end_date):
            if single_date.isoweekday() == days[instance.day]:
                try:
                    AttendanceClass.objects.get(date=single_date.strftime("%Y-%m-%d"), assign=instance.assign)
                except AttendanceClass.DoesNotExist:
                    a = AttendanceClass(date=single_date.strftime("%Y-%m-%d"), assign=instance.assign)
                    a.save()


class NotificationStudent(models.Model):
    student_id = models.ForeignKey(Student, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.student_id)
 
class NotificationTeacher(models.Model):
    teacher_id = models.ForeignKey(Teacher, on_delete=models.CASCADE)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

sams/samsApp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from .models import User
# from .models import User, Dept, Class, Student, Attendance, Course, Teacher, Assign, AttendanceTotal, time_slots, DAYS_OF_WEEK, AssignTime, AttendanceClass, StudentCourse, NotificationStudent, NotificationTeacher
from django.forms import ModelForm



class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name','last_name','email','is_teacher','is_student')

        
# class TeacherForm(ModelForm):
#     class Meta:
#         model = Teacher
#         fields = '__all__'
        
# class StudentForm(ModelForm):
#     class Meta:
#         model = Student
#         fields = '__all__'

# class ClassForm(ModelForm):
#     class Meta:
#         model = Class
#         fields = '__all__'

# class DeptForm(ModelForm):
#     class Meta:
#         model = Dept
#         fields = '__all__'

# class NotificationStudentForm(ModelForm):
#     class Meta:
#         model = NotificationStudent
#         fields = '__all__'   

# class NotificationTeacherForm(ModelForm):
#     class Meta:
#         model = NotificationTeacher
#         fields = '__all__'  

# class CourseForm(ModelForm):
#     class Meta:
#         model = Course
#         fields = '__all__'  


sams/samsApp/templates/change_password.html
{% load static %}
{% load avatar_tags %}
{% load crispy_forms_tags %}

{% include "header.html" %}

{% if request.user.is_authenticated %}
{% if request.user.is_student%}
{% include "student_header.html" %}

  <div class="container-fluid">

            <div class="row justify-content-center pb-5">
                <div class="col-sm-6 mx-4">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
        
                        <div class="card-header bg-info text-white"><h3 class="text-center font-weight-light my-4">Change Password</h3></div>
                        <div class="card-body">
                            <form method="POST" action="">
                                {% csrf_token %}
                                <div class="row mb-3 ">
                                    {{form|crispy}}        
                                </div>
                                    <div class="mt-4 text-center">
                                        <input type="submit" class="btn btn-outline-warning" value="Change Password">
                                    </div>
                            </form> 
                        </div>
                        {% if messages %}
                        <div class="card-footer text-muted">
                            {% for message in messages %}
                            <p class="text-danger" >{{message}}</p>
                            {% endfor %}
                        </div>
                        {% endif %}
                        </div>
                </div>
            </div>
  </div>

  {% else %}
  <p>You're not allowed  in this page - <a href={% url 'login_url' %}>login</a>?</p>
  {% endif %}
  {% else %}
  <p>You're already logged in. Would you like to <a href={% url login_url %}>login</a>?</p>
  {% endif %}

{% include "footer.html" %}

sams/samsApp/templates/login_page.html
{% extends 'logBase.html' %}
{% load static %}
{% block content%}
<style>
    @keyframes rotation {
  from {
    transform: rotate(-5deg);
  }
  to{
    transform: rotate(5deg);
  }
 
}
.anim {
  animation: 4s linear infinite rotation;
  animation-timing-function: linear;
}
</style>
<div class="container" style="overflow-x:hidden;" >
    <div class="row">
        <div class="col-sm-5 my-5 anim shadow">
            <img src="{% static 'images/Group171.svg' %}" alt="" class="img-fluid ">

        </div>
        <div class="col-sm-6 mx-2">
            <div class="card shadow-lg border-0 rounded-lg mt-5">

                <div class="card-header bg-info text-white"><h3 class="text-center font-weight-light my-4">Login</h3></div>
                <div class="card-body">
                    <form method="POST" action="">
                        {% csrf_token %}
                       <div class=" mb-3 d-flex">
                            <label for="inputUsername" class="mx-4 fw-bold">Email</label>
                            <input name="email" class="form-control mx-3" id="inputUsername" type="text" placeholder="example@gmail.com" />
                          
                        </div>
                        <div class=" mb-3 d-flex">
                            <label for="inputPassword" class="mx-2 fw-bold">Password</label>
                            <input name="password" class="form-control mx-3" id="inputPassword" type="password" placeholder="password" />
                            
                        </div> 
                        <div class="mt-4 mb-0 text-center">
                            <input type="submit" class="btn btn-outline-warning text-dark" value="Login">
                        </div>
                    </form>
                </div>
                {% if messages %}
                <div class="card-footer text-muted">
                    {% for message in messages %}
                    <p class="text-danger" >{{message}}</p>
                    {% endfor %}
                </div>
                {% endif %}
    
                <div div class="card-footer text-center py-3">
                    <a class="btn btn-outline-info text-dark"  href={% url 'password_reset' %}>Forget password?</a>
                </div>
    </div>
        </div>
   
    </div>
    <br/><br/>
    <footer class="border-top">
        <p class="text-center text-muted pt-4">Copyright © 2023<a href="https://www.bootstrapdash.com/" class="px-1">Seams</a>All rights reserved.</p>

       
      </footer>
</div>

           
{% endblock content%}

sams/samsApp/templates/registration.html
{% extends 'logBase.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content%}
<style>
    @keyframes rotation {
  from {
    transform: rotate(-5deg);
  }
  to{
    transform: rotate(5deg);
  }
 
}
.anim {
  animation: 4s linear infinite rotation;
  animation-timing-function: linear;
}
</style>

        <div class="row" style="margin-top: -120px; overflow-x: hidden;" >
            <div class="col-md-5 mt-5 mx-3 anim">
                <img src="{% static 'images/Group171.svg' %}" alt="" class="img-fluid ">

            </div>
            <div class="col-md-6 my-0"  style="overflow-x: hidden;">
                <div class="card shadow border-0 rounded-lg mt-5 " >
                    <div class="card-header bg-info text-light"><h3 class="text-center text-light font-weight-light my-4">Create Account</h3></div>
                    <div class="card-body">
                        <form method="POST" action="">
                            {% csrf_token %}
                            <div class="row mb-3 ">
                                {{form|crispy}}        
                            </div>
                                <div class="mt-4 text-center">
                                    <input type="submit" class="btn btn-outline-warning" value="Create Account">
                                </div>
                        </form> 
        
                    </div>
                    <div class="p-3">   
                        {% if messages %}
                        <div class="col-12">
                        {% for message in messages %}
                        {% if message.tags == "error" %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-top: 10px;">
                            <b>{{ message }}</b>
                            <button type="button" class="btn-close " data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                        {% endif %}
                        {% endfor %}
                        </div>
                        {% endif %}
                    </div>
                    
                    <div class="card-footer text-center py-3">
                        <div class="small"><a href={% url 'login_url' %} class = "text-dark text-decoration-none">Have an account? <span class="text-danger">login</span></a></div>
                    </div>
                </div>
                <br/><br/>
            </div>
          
            <footer class="border-top">
                <p class="text-center text-muted pt-4">Copyright © 2023<a href="https://www.bootstrapdash.com/" class="px-1">Seams</a>All rights reserved.</p>
        
               
              </footer>
        </div>       
      
                       
{% endblock content%}

sams/samsApp/templates/student_header.html
{% load static %}
<head>
  <title>Sams Atendance Management System</title>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="{% static 'images/favicon.png' %}" rel="icon" type="image/x-icon" />
</head>
<body class="bg-light">
  <header id="header-section">
   
    <nav class="navbar navbar-expand-lg pl-3 pl-sm-0" id="navbar">
        <div class="container">
          <div class="navbar-brand-wrapper d-flex mx-3 my-0" >
            <img class="img-responsive h-25 rounded-circle " style="width: 160px;" src="{% static 'images/logo.png' %}" alt="">
           
          </div>
          <button class="navbar-toggler " type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse mx-5" id="navbarNavDropdown" >
            <ul class="navbar-nav d-flex">
              <li class="nav-item mx-1">
                <a class="active nav-link fw-bold text-danger " aria-current="page" href="{% url 'student_home_url' %}">Home</a>
              </li>
              <li class="nav-item mx-3">
                <a class="nav-link fw-bold" href="{% url 'student_attendance_url' request.user.student.USN %}">Attendance</a>
              </li>
              <li class="nav-item mx-1 d-flex">
                <a class="nav-link fw-bold" href="{% url 'student_notification_url' request.user.student.USN %}">Notification</a>
                <span class="text-light btn btn-danger rounded-circle" >{{note}}</span>
              </li>
              <li class="nav-item mx-1"></li>
              <div class="col-lg-2  col-sm-3  align-self-center text-white mx-5"  >
                <a class="nav-link   btn btn-md btn-outline-warning  "  href="{% url 'logout_url' %}">Sign out
                </a>
            </div>
         
          </ul>
        </div>


        </div> 
    </nav>   
  
  </header>

sams/samsApp/templates/student_home.html

{% load static %}
{% load avatar_tags %}
{% include "header.html" %}


{% if request.user.is_authenticated %}
{% if request.user.is_student%}
{% include "student_header.html" %}

  <div class="container-fluid pb-4" style="margin-top: -10px;">
          <div class="row my-3">
            <div class="col d-flex justify-content-end">
              <div class="align-self-center"><a class="btn btn-info text-light " role="button" href="{% url 'student_change_password' %}">Change password</a></div>
              <div class="align-self-center mx-3 text-danger">Change your profile</div>
              <a href="{% url 'avatar_change' %}">{% avatar user 65 class="rounded-circle" id="user_avatar" %}
              </a>
            </div>
          </div>

            <div class="row ">
              <div class="col d-flex justify-content-lg-end justify-content-md-end my-2">
                {% avatar user 65 class="rounded-circle" id="user_avatar" %}
              </div>
            
              <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4 ">
                <div class="pt-3 pb-2 mb-3 border-bottom ">
                  <h1 class="h3 text-info text-uppercase">{{ request.user.first_name }} {{request.user.last_name}} </h1>
                  <p class="text-small text-success">Logged as a student</p>
                </div>

                <div class="card mx-5 shadow-lg">
                  <div class="card-body ">
                    <div class="bg-light rounded-lg p-3 ">
                            <h1 class="display-4 fw-1200 f">Good to see you again &#128516; {{ request.user.first_name }}</h1>
                            <p class="lead text-darks ">View the attendance status for each of your courses.</p>
                            <hr class="my-4 border-warning py-3">
                            
                            <a class="btn btn-outline-info btn-lg" role="button" href="{% url 'student_attendance_url' request.user.student.USN %}"> View Attendance</a>
                        
                          </div>
                        </div>
                      </div>
              </main> 
            </div>
  </div>

  {% else %}
  <p>You're not allowed  in this page - <a href={% url 'login_url' %}>login</a>?</p>
  {% endif %}
  {% else %}
  <p>You're already logged out. Would you like to <a href={% url login_url %}>login</a>?</p>
  {% endif %}
{% include "footer.html" %}

sams/samsApp/templates/teacher_attendance.html

{% load static %}
{% load avatar_tags %}

{% include "header.html" %}
{% include "teacher_header.html" %}

<div class="container-fluid">
  

  <div class="row py-3">
    <div class="col d-flex justify-content-md-end justify-content-lg-end">
      {% avatar user 65 class="rounded-circle" id="user_avatar" %}
    </div>


<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <div class=" align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2 text-capitalize text-info ">{{ request.user.first_name }} {{ request.user.last_name }}</h1>
  </div>


  <div class="container-fluid">
    <div class="row g-5">

        <div class="col">
            <div class="card shadow-lg text-center">
                <div class="card-header bg-info fw-bold text-light h5 ">
                  Attendace Table
                </div>
                <div class="card-body">
                  {% if c.student_set.all %}

                  <form action="{% url 'confirm_url' assc.id %}" method="post">
                              {% csrf_token %}
                      <div class="card mb-3">
                             <div class="card-body">
                            <div class="table-responsive">
                              <table class="table table-hover">
                                <thead >
                                  <tr>
                                      <th>Student name</th>
                                      <th></th>
                                  </tr>
                                </thead>
                                  <tbody>
                                  {% for s in c.student_set.all %}
                                      <tr>
                                      <td class="text-capitalize">{{s.user.first_name}} {{s.user.last_name}}</td>
                                      <td>
                                          <div class="btn-group btn-group-toggle" data-toggle="buttons">
                  
                                                  <label class="btn btn-sm btn-outline-info text-dark fw-bold mx-2">
                                                      <input type="radio" name="{{ s.USN }}"   value="present" checked> Present
                                                  </label>
                  
                                                  <label class="btn btn-sm btn-outline-warning text-dark fw-bold">
                                                      <input type="radio" name="{{ s.USN }}" value="absent"> Absent
                                                  </label>
                                          </div>
                                      </td>
                                      </tr>
                                  {% endfor %}
                                  </tbody>
                              </table>
                            </div>
                          </div>
                        </div>
                  
                  
                      <input class="btn btn-info text-dark fw-bold my-4" type="submit" value="Submit">
                    
                  </form>
                  
                  
                   {% else %}
                      <p>No students in Class</p>
                  {% endif %} 
                </div>
                
            </div>
          
        </div>

        
        
        
        
        
    </div>

</div> 
</main> 
</div>
</div>

{% include "footer.html" %}

sams/samsApp/templates/teacher_change_password.html
{% load static %}
{% load avatar_tags %}
{% load crispy_forms_tags %}

{% include "header.html" %}
{% if request.user.is_authenticated %}
{% if request.user.is_teacher %}
{% include "teacher_header.html" %}

  <div class="container-fluid">

            <div class="row justify-content-center pb-5">
                <div class="col-sm-6 mx-4">
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
        
                        <div class="card-header bg-info text-white"><h3 class="text-center font-weight-light my-4">Change Password</h3></div>
                        <div class="card-body">
                            <form method="POST" action="">
                                {% csrf_token %}
                                <div class="row mb-3 ">
                                    {{form|crispy}}        
                                </div>
                                    <div class="mt-4 text-center">
                                        <input type="submit" class="btn btn-outline-warning" value="Change Password">
                                    </div>
                            </form> 
                        </div>
                        {% if messages %}
                        <div class="card-footer text-muted">
                            {% for message in messages %}
                            <p class="text-danger" >{{message}}</p>
                            {% endfor %}
                        </div>
                        {% endif %}
                        </div>
                </div>
            </div>
  </div>
  {% else %}
  <p>You're not allowed  in this page - <a href={% url 'login_url' %}>login</a>?</p>
  {% endif %}
  {% else %}
  <p>You're already logged out. Would you like to <a href={% url login_url %}>login</a>?</p>
  {% endif %}
{% include "footer.html" %}